name: Docker

on:
  schedule:
    - cron: '0 0 * * *'
    - cron: '30 2 * * *'
    - cron: '15 5 * * *' 
  workflow_dispatch:

env:
  QUERY_TYPE: "high-cpu-all"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker
        uses: docker/setup-docker-action@v4
      - name: Cycle
        run: |
          RANDOM_NUM=$((RANDOM % 50 + 10))
          for i in $(seq 1 $RANDOM_NUM); do
            docker pull kwdb/kwdb
            docker rmi kwdb/kwdb || true
            echo "Completed cycle $i"
          done
      -
        name: Docker run
        run: |
          docker run -d --privileged --name kaiwudb \
            --ulimit memlock=-1 \
            -p 26257:26257 \
            -p 8080:8080 \
             -v /var/lib/kaiwudb:/kaiwudb/deploy/kaiwudb-container \
            --ipc shareable \
            -w /kaiwudb/bin \
            kwdb/kwdb \
            ./kwbase start-single-node \
                --insecure \
                --listen-addr=0.0.0.0:26257 \
                --http-addr=0.0.0.0:8080 \
                --store=/kaiwudb/deploy/kaiwudb-container
      - 
        name: Check out
        uses: actions/checkout@v4
        with:
          repository: KWDB/kwdb-tsbs
          path: kwdb-tsbs
          fetch-depth: 0
      - uses: actions/setup-go@v5
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
              kwdb-tsbs/go.sum
              ~/go/pkg/mod
              ~/.cache/go-build
          key: ${{ runner.os }}-kwdb-tsbs-${{ hashFiles('kwdb-tsbs/go.sum') }}
          restore-keys: |
              ${{ runner.os }}-kwdb-tsbs-
      - name: Make
        working-directory: ./kwdb-tsbs
        run: |
          make generators tsbs_load_kwdb tsbs_run_queries_kwdb
      -
        name: Generate Data
        working-directory: ./kwdb-tsbs/bin/
        run: |
          ./tsbs_generate_data \
              --format="kwdb" \
              --use-case="cpu-only" \
              --seed=123 \
              --scale=100 \
              --timestamp-start="2023-01-01T00:00:00Z" \
              --timestamp-end="2023-01-02T01:00:00Z" \
              --log-interval="10s" \
              --orderquantity=12 > data.dat
      -
        name: Load Data
        working-directory: ./kwdb-tsbs/bin/
        run: |
          ./tsbs_load_kwdb \
              --file=data.dat \
              --user=root \
              --pass= \
              --host=127.0.0.1 \
              --port=26257 \
              --insert-type=insert \
              --batch-size=1000 \
              --db-name=benchmark \
              --case=cpu-only \
              --workers=12 \
              --partition=false
      -
        name: Generate Queries
        working-directory: ./kwdb-tsbs/bin/
        run: |
         ./tsbs_generate_queries \
              --format="kwdb" \
              --use-case="cpu-only" \
              --seed=123 \
              --scale=100 \
              --timestamp-start="2023-01-01T00:00:00Z" \
              --timestamp-end="2023-01-05T01:00:00Z" \
              --query-type=${QUERY_TYPE} \
              --queries=100 \
              --db-name=benchmark > query.dat
      -
        name: Run Queries
        working-directory: ./kwdb-tsbs/bin/
        run: |
         ./tsbs_run_queries_kwdb \
              --file=query.dat \
              --user=root \
              --pass= \
              --host=127.0.0.1 \
              --port=26257 \
              --query-type=${QUERY_TYPE} \
              --workers=1
      -
        name: Docker exec
        run: |
          docker exec kaiwudb ./kwbase sql --insecure --host=127.0.0.1 -e "CREATE DATABASE IF NOT EXISTS testdb;"
          docker exec kaiwudb ./kwbase sql --insecure --host=127.0.0.1 -e "CREATE TABLE IF NOT EXISTS testdb.public.testtable (id INT PRIMARY KEY, name VARCHAR(255));"
          docker exec kaiwudb ./kwbase sql --insecure --host=127.0.0.1 -e "INSERT INTO testdb.public.testtable (id, name) VALUES (1, 'John Doe');"
          docker exec kaiwudb ./kwbase sql --insecure --host=127.0.0.1 -e "INSERT INTO testdb.public.testtable (id, name) VALUES (2, 'Jane Doe');"
          docker exec kaiwudb ./kwbase sql --insecure --host=127.0.0.1 -e "SELECT * FROM testdb.public.testtable;"
