name: Docker

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker
        uses: docker/setup-docker-action@v4
      -
        name: Docker run
        run: |
          docker run -d --privileged --name kaiwudb \
            --ulimit memlock=-1 \
            -p 26257:26257 \
            -p 8080:8080 \
             -v /var/lib/kaiwudb:/kaiwudb/deploy/kaiwudb-container \
            --ipc shareable \
            -w /kaiwudb/bin \
            kwdb/kwdb:2.2.0 \
            ./kwbase start-single-node \
                --insecure \
                --listen-addr=0.0.0.0:26257 \
                --http-addr=0.0.0.0:8080 \
                --store=/kaiwudb/deploy/kaiwudb-container
      -
        name: Docker exec
        run: |
          docker exec -it kaiwudb ./kwbase sql --insecure --host=127.0.0.1 -e "CREATE DATABASE IF NOT EXISTS testdb;"
          docker exec -it kaiwudb ./kwbase sql --insecure --host=127.0.0.1 -e "CREATE TABLE IF NOT EXISTS testdb.public.testtable (id INT PRIMARY KEY, name VARCHAR(255));"
          docker exec -it kaiwudb./kwbase sql --insecure --host=127.0.0.1 -e "INSERT INTO testdb.public.testtable (id, name) VALUES (1, 'John Doe');"
          docker exec -it kaiwudb./kwbase sql --insecure --host=127.0.0.1 -e "INSERT INTO testdb.public.testtable (id, name) VALUES (2, 'Jane Doe');"
          docker exec -it kaiwudb./kwbase sql --insecure --host=127.0.0.1 -e "SELECT * FROM testdb.public.testtable;"
