name: Ubuntu

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

env:
  KWDB_URL: "https://github.com/KWDB/KWDB/releases/download/V2.2.0/KWDB-2.2.0-ubuntu22.04-x86_64-debs.tar.gz"

jobs:
  ubuntu:
    runs-on: ubuntu-22.04
    steps:
      - name: Download KWDB
        run: |
          wget ${KWDB_URL}
          tar -xzvf KWDB-2.2.0-ubuntu22.04-x86_64-debs.tar.gz
      - name: Configure KWDB
        working-directory: ./kwdb_install
        run: |
          cat > deploy.cfg <<EOF
          [global]
          secure_mode=tls
          management_user=kaiwudb
          rest_port=8080
          kaiwudb_port=29257
          data_root=/var/lib/kaiwudb
          cpu=1
          encrypto_store=true

          [local]
          node_addr=127.0.0.1
          EOF
      - name: install KWDB
        working-directory: ./kwdb_install
        run: |
          cat deploy.cfg
          sudo apt update
          sudo apt install libprotobuf23 
          chmod +x ./deploy.sh
          ./deploy.sh install --single
          sudo systemctl daemon-reload
      - name: Start KWDB
        working-directory: ./kwdb_install
        run: |
          ./deploy.sh start
          ./deploy.sh status
      - name: Check Out
        uses: actions/checkout@v4
      - name: Check out KWDB TSBS
        uses: actions/checkout@v4
        with:
          repository: KWDB/kwdb-tsbs
          path: kwdb-tsbs
          fetch-depth: 0
      - uses: actions/setup-go@v5
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
              kwdb-tsbs/go.sum
              ~/go/pkg/mod
              ~/.cache/go-build
          key: ${{ runner.os }}-kwdb-tsbs-${{ hashFiles('kwdb-tsbs/go.sum') }}
          restore-keys: |
              ${{ runner.os }}-kwdb-tsbs-
      - name: Make
        working-directory: ./kwdb-tsbs
        run: |
            make
      - name: mv script
        run: |
          mv -f ./tsbs_kwdb.sh ./kwdb-tsbs/scripts/tsbs_kwdb.sh
      - name: Auto Script
        working-directory: ./kwdb-tsbs/scripts/
        run: |
          sudo workspace="/usr/local/kaiwudb" ./tsbs_kwdb.sh
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: kwdb-tsbs-report
          path: kwdb-tsbs/reports/
