name: Ubuntu

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

env:
  KWDB_URL: "https://github.com/KWDB/KWDB/releases/download/V2.2.0/KWDB-2.2.0-ubuntu22.04-x86_64-debs.tar.gz"
  JDBC: "https://github.com/KWDB/KWDB/releases/download/V2.2.0/kaiwudb-jdbc-2.2.0.jar"
  KAFKA: "https://github.com/KWDB/KWDB/releases/download/V2.2.0/KaiwuDB-Kafka-Connect-2.0.2.zip"
  DATAX: "https://github.com/KWDB/KWDB/releases/download/V2.2.0/KaiwuDB_datax-2.2.0.zip"
  KDC_X86: "https://github.com/KWDB/KWDB/releases/download/V2.2.0/KaiwuDB_Developer_Center-2.0.4-linux-x86_64.tar.gz"
  KDC_MAC: "https://github.com/KWDB/KWDB/releases/download/V2.2.0/KaiwuDB_Developer_Center-2.0.4-mac-x86_64.tar.gz"
  KDC_WIN: "https://github.com/KWDB/KWDB/releases/download/V2.2.0/KaiwuDB_Developer_Center-2.0.4-win-x86_64.zip"
  KY_ARM: "https://github.com/KWDB/KWDB/releases/download/V2.2.0/KWDB-2.2.0-kylinV10_2403-aarch64-rpms.tar.gz"
  KY_X86: "https://github.com/KWDB/KWDB/releases/download/V2.2.0/KWDB-2.2.0-kylinV10_2403-x86_64-rpms.tar.gz"
  UB_20_X86: "https://github.com/KWDB/KWDB/releases/download/V2.2.0/KWDB-2.2.0-ubuntu20.04-x86_64-debs.tar.gz"
  UB_20_ARM: "https://github.com/KWDB/KWDB/releases/download/V2.2.0/KWDB-2.2.0-ubuntu22.04-aarch64-docker.tar.gz"
  UB_22_ARM: "https://github.com/KWDB/KWDB/releases/download/V2.2.0/KWDB-2.2.0-ubuntu22.04-x86_64-docker.tar.gz"

jobs:
  ubuntu:
    runs-on: ubuntu-22.04
    steps:
      - name: Download KWDB
        run: |
          wget ${KWDB_URL}
          wget ${JDBC}
          wget ${KAFKA}
          wget ${DATAX}
          wget ${KDC_X86}
          wget ${KDC_MAC}
          wget ${KDC_WIN}
          wget ${KY_ARM} 
          wget ${KY_X86}
          wget ${UB_20_X86}
          wget ${UB_20_ARM}
          wget ${UB_22_ARM}
          tar -xzvf KWDB-2.2.0-ubuntu22.04-x86_64-debs.tar.gz
      - name: Configure KWDB
        working-directory: ./kwdb_install
        run: |
          cat > deploy.cfg <<EOF
          [global]
          secure_mode=tls
          management_user=kaiwudb
          rest_port=8080
          kaiwudb_port=29257
          data_root=/var/lib/kaiwudb
          cpu=1
          encrypto_store=true

          [local]
          node_addr=127.0.0.1
          EOF
      - name: install KWDB
        working-directory: ./kwdb_install
        run: |
          cat deploy.cfg
          sudo apt update
          sudo apt install libprotobuf23 
          chmod +x ./deploy.sh
          ./deploy.sh install --single
          sudo systemctl daemon-reload
      - name: Start KWDB
        working-directory: ./kwdb_install
        run: |
          ./deploy.sh start
          ./deploy.sh status
      - name: Check Out
        uses: actions/checkout@v4
      - name: Check out KWDB TSBS
        uses: actions/checkout@v4
        with:
          repository: KWDB/kwdb-tsbs
          path: kwdb-tsbs
          fetch-depth: 0
      - uses: actions/setup-go@v5
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
              kwdb-tsbs/go.sum
              ~/go/pkg/mod
              ~/.cache/go-build
          key: ${{ runner.os }}-kwdb-tsbs-${{ hashFiles('kwdb-tsbs/go.sum') }}
          restore-keys: |
              ${{ runner.os }}-kwdb-tsbs-
      - name: Make
        working-directory: ./kwdb-tsbs
        run: |
            make generators tsbs_load_kwdb tsbs_run_queries_kwdb
      - name: mv script
        run: |
          mv -f ./tsbs_kwdb.sh ./kwdb-tsbs/scripts/tsbs_kwdb.sh
      - name: Auto Script
        working-directory: ./kwdb-tsbs/scripts/
        run: |
          sudo workspace="/usr/local/kaiwudb" ports=29257 ./tsbs_kwdb.sh
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: kwdb-tsbs-report
          path: kwdb-tsbs/reports/
